// Auto-generated by scripts/generate-jobs.ts — do not edit manually
import exampleLog from './example-log.js'
import sendEmail from './send-email.js'

export const allJobs = [exampleLog, sendEmail] as const
