import fs from 'node:fs'
import path from 'node:path'

const DEFINITIONS_DIR = path.resolve(import.meta.dirname, '../src/jobs/definitions')
const BARREL_FILE = path.join(DEFINITIONS_DIR, 'index.ts')

function toCamelCase(filename: string): string {
  return filename
    .replace(/\.ts$/, '')
    .replace(/-([a-z])/g, (_, c: string) => c.toUpperCase())
}

function toJobName(filename: string): string {
  return filename.replace(/\.ts$/, '')
}

function getDefinitionFiles(): string[] {
  if (!fs.existsSync(DEFINITIONS_DIR)) {
    fs.mkdirSync(DEFINITIONS_DIR, { recursive: true })
  }
  return fs
    .readdirSync(DEFINITIONS_DIR)
    .filter((f) => f.endsWith('.ts') && !f.startsWith('_') && f !== 'index.ts')
    .sort()
}

function scaffoldEmpty(filename: string) {
  const filePath = path.join(DEFINITIONS_DIR, filename)
  const content = fs.readFileSync(filePath, 'utf-8').trim()

  if (content.length > 0) return

  const jobName = toJobName(filename)
  const template = `import { defineJob } from '../../lib/queue.js'

export default defineJob({
  name: '${jobName}',
  handler: async (payload: Record<string, unknown> /* Add your types */) => {
    // TODO: implement ${jobName}
  },
})
`

  fs.writeFileSync(filePath, template)
  console.log(`[jobs] Scaffolded ${filename}`)
}

function generateBarrel(files: string[]) {
  const imports = files.map((f) => {
    const varName = toCamelCase(f)
    return `import ${varName} from './${f.replace(/\.ts$/, '.js')}'`
  })

  const varNames = files.map((f) => toCamelCase(f))

  const content = `// Auto-generated by scripts/generate-jobs.ts — do not edit manually
${imports.join('\n')}

export const allJobs = [${varNames.join(', ')}] as const
`

  // Guard against duplicate fs.watch events — macOS fires multiple events per file operation
  const existing = fs.existsSync(BARREL_FILE) ? fs.readFileSync(BARREL_FILE, 'utf-8') : ''
  if (existing === content) return

  fs.writeFileSync(BARREL_FILE, content)
  console.log(`[jobs] Updated barrel (${files.length} job${files.length === 1 ? '' : 's'})`)
}

function run() {
  const files = getDefinitionFiles()
  for (const file of files) {
    scaffoldEmpty(file)
  }
  generateBarrel(files)
}

if (process.argv.includes('--watch')) {
  // Initial run + watch
  run()
  console.log('[jobs] Watching for changes in definitions/')
  fs.watch(DEFINITIONS_DIR, { persistent: true }, (_event, filename) => {
    if (!filename?.endsWith('.ts') || filename === 'index.ts') return
    if (!fs.existsSync(path.join(DEFINITIONS_DIR, filename))) {
      generateBarrel(getDefinitionFiles())
      return
    }
    scaffoldEmpty(filename)
    generateBarrel(getDefinitionFiles())
  })
} else {
  // One-shot for CI/build or manual run
  run()
}
